import jsPDF from 'jspdf'
import type { Assessment } from '@/types/database'

export interface PatientReportData {
  patient: {
    name: string
    age: number
    gender: string
    diagnosis: string
    admissionDate: string
    onsetDate?: string | null
  }
  assessments: Assessment[]
  language: 'ko' | 'en'
}

const COLORS = {
  primary: [99, 102, 241] as [number, number, number],
  secondary: [16, 185, 129] as [number, number, number],
  warning: [245, 158, 11] as [number, number, number],
  error: [239, 68, 68] as [number, number, number],
  text: [17, 24, 39] as [number, number, number],
  textSecondary: [107, 114, 128] as [number, number, number],
}

interface AssessmentsByType {
  [key: string]: Assessment[]
}

function groupByType(assessments: Assessment[]): AssessmentsByType {
  const map: AssessmentsByType = {}
  assessments.forEach((a) => {
    if (!map[a.assessment_type]) map[a.assessment_type] = []
    map[a.assessment_type].push(a)
  })
  // Sort each type by assessed_at descending (newest first)
  for (const key of Object.keys(map)) {
    map[key].sort((a, b) => new Date(b.assessed_at).getTime() - new Date(a.assessed_at).getTime())
  }
  return map
}

function getScore(a: Assessment): number | null {
  return a.score != null ? Number(a.score) : null
}

function formatDate(dateStr: string, isKo: boolean): string {
  return new Date(dateStr).toLocaleDateString(isKo ? 'ko-KR' : 'en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  })
}

export async function generatePatientReportPdf(data: PatientReportData): Promise<Blob> {
  const { patient, assessments, language } = data
  const isKo = language === 'ko'
  const byType = groupByType(assessments)

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 20
  const contentWidth = pageWidth - margin * 2
  let yPos = margin

  // --- Helper functions ---
  const addText = (
    text: string,
    x: number,
    y: number,
    options?: {
      fontSize?: number
      fontStyle?: 'normal' | 'bold'
      color?: [number, number, number]
      align?: 'left' | 'center' | 'right'
    },
  ) => {
    const { fontSize = 10, fontStyle = 'normal', color = COLORS.text, align = 'left' } = options || {}
    doc.setFontSize(fontSize)
    doc.setFont('helvetica', fontStyle)
    doc.setTextColor(...color)
    doc.text(text, x, y, { align })
  }

  const addLine = (y: number) => {
    doc.setDrawColor(229, 231, 235)
    doc.line(margin, y, pageWidth - margin, y)
  }

  const checkPageBreak = (needed: number) => {
    if (yPos + needed > pageHeight - 25) {
      doc.addPage()
      yPos = margin
    }
  }

  const addSection = (title: string) => {
    checkPageBreak(30)
    yPos += 10
    addText(title, margin, yPos, { fontSize: 14, fontStyle: 'bold', color: COLORS.primary })
    yPos += 8
    addLine(yPos)
    yPos += 8
  }

  const addFooter = () => {
    const footerY = pageHeight - 12
    addLine(footerY - 5)
    addText(
      isKo
        ? 'PoseRehab에서 생성됨 | 이 리포트는 참고용이며 의료 조언을 대체하지 않습니다.'
        : 'Generated by PoseRehab | This report is for reference only and does not replace medical advice.',
      pageWidth / 2,
      footerY,
      { fontSize: 7, color: COLORS.textSecondary, align: 'center' },
    )
  }

  // --- Header ---
  doc.setFillColor(...COLORS.primary)
  doc.rect(0, 0, pageWidth, 40, 'F')

  addText('PoseRehab', pageWidth / 2, 18, {
    fontSize: 24,
    fontStyle: 'bold',
    color: [255, 255, 255],
    align: 'center',
  })
  addText(isKo ? '환자 종합 리포트' : 'Patient Comprehensive Report', pageWidth / 2, 28, {
    fontSize: 12,
    color: [255, 255, 255],
    align: 'center',
  })

  yPos = 50

  // --- Patient Info ---
  addText(isKo ? '환자명' : 'Patient', margin, yPos, { fontStyle: 'bold' })
  addText(patient.name, margin + 30, yPos)

  addText(isKo ? '나이/성별' : 'Age/Gender', pageWidth / 2, yPos, { fontStyle: 'bold' })
  addText(`${patient.age}${isKo ? '세' : 'y'} / ${patient.gender}`, pageWidth / 2 + 30, yPos)
  yPos += 6

  addText(isKo ? '진단명' : 'Diagnosis', margin, yPos, { fontStyle: 'bold' })
  addText(patient.diagnosis, margin + 30, yPos)

  addText(isKo ? '입원일' : 'Admitted', pageWidth / 2, yPos, { fontStyle: 'bold' })
  addText(formatDate(patient.admissionDate, isKo), pageWidth / 2 + 30, yPos)
  yPos += 3

  addLine(yPos)
  yPos += 3

  addText(
    `${isKo ? '생성일' : 'Generated'}: ${new Date().toLocaleDateString(isKo ? 'ko-KR' : 'en-US', { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' })}`,
    margin,
    yPos,
    { fontSize: 8, color: COLORS.textSecondary },
  )
  yPos += 5

  // === Section 1: Latest Score Summary Table ===
  addSection(isKo ? '평가 점수 요약' : 'Assessment Score Summary')

  const scoreEntries: { name: string; maxLabel: string; score: string; date: string }[] = []

  const addScoreEntry = (type: string, name: string, maxLabel: string, scoreFn: (a: Assessment) => string) => {
    const items = byType[type]
    if (items && items.length > 0) {
      const latest = items[0]
      scoreEntries.push({
        name,
        maxLabel,
        score: scoreFn(latest),
        date: formatDate(latest.assessed_at, isKo),
      })
    }
  }

  addScoreEntry('BBS', 'BBS (Berg Balance Scale)', '/56', (a) => `${getScore(a) ?? '-'}/56`)
  addScoreEntry('FAC', 'FAC (Functional Ambulation)', 'Level 0-5', (a) => `Level ${getScore(a) ?? '-'}`)
  addScoreEntry('MBI', 'MBI (Modified Barthel Index)', '/100', (a) => `${getScore(a) ?? '-'}/100`)
  addScoreEntry('MMT', 'MMT (Manual Muscle Testing)', 'Grade 0-5', (a) => {
    const d = a.details as Record<string, unknown> | null
    const scores = d?.scores as Record<string, { lt: number | null; rt: number | null }> | undefined
    if (!scores) return '-'
    const count = Object.keys(scores).length
    return `${count} ${isKo ? '근육군' : 'muscles'}`
  })
  addScoreEntry('ROM', 'ROM (Range of Motion)', '', (a) => {
    const d = a.details as Record<string, unknown> | null
    const scores = d?.scores as Record<string, unknown> | undefined
    if (!scores) return '-'
    return `${Object.keys(scores).length} ${isKo ? '관절' : 'joints'}`
  })
  addScoreEntry('HandFunction', isKo ? '손기능 (Hand Function)' : 'Hand Function', '/32', (a) => {
    const d = a.details as Record<string, unknown> | null
    const lt = (d?.leftTotalScore as number) ?? '-'
    const rt = (d?.rightTotalScore as number) ?? '-'
    return `Lt.${lt} / Rt.${rt}`
  })
  addScoreEntry('ASIA', 'ASIA (Spinal Cord)', '/100', (a) => {
    const d = a.details as Record<string, unknown> | null
    const motorTotal = (d?.motorTotal as number) ?? '-'
    const aisGrade = (d?.aisGrade as string) ?? '-'
    return `Motor ${motorTotal}, Grade ${aisGrade}`
  })

  if (scoreEntries.length > 0) {
    // Table header
    const col1 = margin
    const col2 = margin + 75
    const col3 = margin + 120

    addText(isKo ? '평가 항목' : 'Assessment', col1, yPos, { fontStyle: 'bold', fontSize: 9 })
    addText(isKo ? '최신 점수' : 'Latest Score', col2, yPos, { fontStyle: 'bold', fontSize: 9 })
    addText(isKo ? '측정일' : 'Date', col3, yPos, { fontStyle: 'bold', fontSize: 9 })
    yPos += 3
    addLine(yPos)
    yPos += 5

    scoreEntries.forEach((entry) => {
      checkPageBreak(10)
      addText(entry.name, col1, yPos, { fontSize: 9 })
      addText(entry.score, col2, yPos, { fontSize: 9, fontStyle: 'bold' })
      addText(entry.date, col3, yPos, { fontSize: 9, color: COLORS.textSecondary })
      yPos += 6
    })
  } else {
    addText(isKo ? '아직 평가 기록이 없습니다.' : 'No assessment records yet.', margin, yPos, {
      color: COLORS.textSecondary,
    })
    yPos += 8
  }

  // === Section 2: First vs Latest Comparison ===
  const typesWithMultiple = Object.entries(byType).filter(([, items]) => items.length >= 2)

  if (typesWithMultiple.length > 0) {
    addSection(isKo ? '최초 vs 최근 비교' : 'First vs Latest Comparison')

    const col1 = margin
    const col2 = margin + 55
    const col3 = margin + 85
    const col4 = margin + 115
    const col5 = margin + 140

    addText(isKo ? '항목' : 'Type', col1, yPos, { fontStyle: 'bold', fontSize: 9 })
    addText(isKo ? '최초' : 'First', col2, yPos, { fontStyle: 'bold', fontSize: 9 })
    addText(isKo ? '최근' : 'Latest', col3, yPos, { fontStyle: 'bold', fontSize: 9 })
    addText(isKo ? '변화' : 'Change', col4, yPos, { fontStyle: 'bold', fontSize: 9 })
    addText(isKo ? '경향' : 'Trend', col5, yPos, { fontStyle: 'bold', fontSize: 9 })
    yPos += 3
    addLine(yPos)
    yPos += 5

    const addComparisonRow = (
      label: string,
      firstVal: string,
      latestVal: string,
      diff: number | null,
    ) => {
      checkPageBreak(10)
      addText(label, col1, yPos, { fontSize: 9 })
      addText(firstVal, col2, yPos, { fontSize: 9, color: COLORS.textSecondary })
      addText(latestVal, col3, yPos, { fontSize: 9, fontStyle: 'bold' })

      if (diff !== null) {
        const diffStr = diff > 0 ? `+${diff}` : `${diff}`
        const diffColor: [number, number, number] =
          diff > 0 ? COLORS.secondary : diff < 0 ? COLORS.error : COLORS.textSecondary
        addText(diffStr, col4, yPos, { fontSize: 9, fontStyle: 'bold', color: diffColor })
        const arrow = diff > 0 ? '↑' : diff < 0 ? '↓' : '→'
        addText(arrow, col5, yPos, { fontSize: 12, fontStyle: 'bold', color: diffColor })
      }
      yPos += 6
    }

    typesWithMultiple.forEach(([type, items]) => {
      const first = items[items.length - 1] // oldest
      const latest = items[0] // newest

      switch (type) {
        case 'BBS': {
          const f = getScore(first) ?? 0
          const l = getScore(latest) ?? 0
          addComparisonRow('BBS', `${f}/56`, `${l}/56`, l - f)
          break
        }
        case 'FAC': {
          const f = getScore(first) ?? 0
          const l = getScore(latest) ?? 0
          addComparisonRow('FAC', `Lv.${f}`, `Lv.${l}`, l - f)
          break
        }
        case 'MBI': {
          const f = getScore(first) ?? 0
          const l = getScore(latest) ?? 0
          addComparisonRow('MBI', `${f}/100`, `${l}/100`, l - f)
          break
        }
        case 'HandFunction': {
          const fd = first.details as Record<string, unknown> | null
          const ld = latest.details as Record<string, unknown> | null
          const fLt = (fd?.leftTotalScore as number) ?? 0
          const lLt = (ld?.leftTotalScore as number) ?? 0
          const fRt = (fd?.rightTotalScore as number) ?? 0
          const lRt = (ld?.rightTotalScore as number) ?? 0
          addComparisonRow(isKo ? '손기능(Lt)' : 'Hand(Lt)', `${fLt}`, `${lLt}`, lLt - fLt)
          addComparisonRow(isKo ? '손기능(Rt)' : 'Hand(Rt)', `${fRt}`, `${lRt}`, lRt - fRt)
          break
        }
        case 'ASIA': {
          const fd = first.details as Record<string, unknown> | null
          const ld = latest.details as Record<string, unknown> | null
          const fMotor = (fd?.motorTotal as number) ?? 0
          const lMotor = (ld?.motorTotal as number) ?? 0
          addComparisonRow('ASIA Motor', `${fMotor}`, `${lMotor}`, lMotor - fMotor)
          const fGrade = (fd?.aisGrade as string) ?? '-'
          const lGrade = (ld?.aisGrade as string) ?? '-'
          addComparisonRow('AIS Grade', fGrade, lGrade, null)
          break
        }
        case 'MMT': {
          const fd = first.details as Record<string, unknown> | null
          const ld = latest.details as Record<string, unknown> | null
          const fScores = fd?.scores as Record<string, { lt: number | null; rt: number | null }> | undefined
          const lScores = ld?.scores as Record<string, { lt: number | null; rt: number | null }> | undefined
          const countGoodPlus = (scores?: Record<string, { lt: number | null; rt: number | null }>) => {
            if (!scores) return 0
            return Object.values(scores).filter((s) => (s.lt ?? 0) >= 4 && (s.rt ?? 0) >= 4).length
          }
          const fGood = countGoodPlus(fScores)
          const lGood = countGoodPlus(lScores)
          addComparisonRow('MMT (Good+)', `${fGood}`, `${lGood}`, lGood - fGood)
          break
        }
        case 'ROM': {
          const fd = first.details as Record<string, unknown> | null
          const ld = latest.details as Record<string, unknown> | null
          const fCount = Object.keys((fd?.scores as Record<string, unknown>) ?? {}).length
          const lCount = Object.keys((ld?.scores as Record<string, unknown>) ?? {}).length
          addComparisonRow('ROM', `${fCount} ${isKo ? '관절' : 'joints'}`, `${lCount} ${isKo ? '관절' : 'joints'}`, null)
          break
        }
      }
    })
  }

  // === Section 3: Score Trend Graph (simple line graph using drawing API) ===
  const trendTypes = ['BBS', 'FAC', 'MBI'] as const
  const trendConfigs = {
    BBS: { label: 'BBS', max: 56, color: [37, 99, 235] as [number, number, number] },
    FAC: { label: 'FAC', max: 5, color: [217, 119, 6] as [number, number, number] },
    MBI: { label: 'MBI', max: 100, color: [16, 185, 129] as [number, number, number] },
  }

  const hasTrendData = trendTypes.some((t) => (byType[t]?.length ?? 0) >= 2)

  if (hasTrendData) {
    addSection(isKo ? '점수 추이 그래프' : 'Score Trend Graph')

    trendTypes.forEach((type) => {
      const items = byType[type]
      if (!items || items.length < 2) return
      const config = trendConfigs[type]

      checkPageBreak(50)

      // Graph area
      const graphX = margin + 10
      const graphY = yPos
      const graphW = contentWidth - 20
      const graphH = 35

      // Label
      addText(config.label, margin, graphY + graphH / 2, { fontSize: 9, fontStyle: 'bold', color: config.color })

      // Axes
      doc.setDrawColor(200, 200, 200)
      doc.line(graphX, graphY + graphH, graphX + graphW, graphY + graphH) // X axis
      doc.line(graphX, graphY, graphX, graphY + graphH) // Y axis

      // Y-axis labels
      addText(`${config.max}`, graphX - 3, graphY + 3, { fontSize: 7, color: COLORS.textSecondary, align: 'right' })
      addText('0', graphX - 3, graphY + graphH, { fontSize: 7, color: COLORS.textSecondary, align: 'right' })

      // Data points (oldest → newest)
      const sorted = [...items].reverse()
      const points: { x: number; y: number; score: number }[] = []

      sorted.forEach((a, i) => {
        const score = getScore(a) ?? 0
        const px = graphX + (i / (sorted.length - 1)) * graphW
        const py = graphY + graphH - (score / config.max) * graphH
        points.push({ x: px, y: py, score })
      })

      // Draw lines
      doc.setDrawColor(...config.color)
      doc.setLineWidth(0.5)
      for (let i = 0; i < points.length - 1; i++) {
        doc.line(points[i].x, points[i].y, points[i + 1].x, points[i + 1].y)
      }

      // Draw dots and score labels
      points.forEach((p) => {
        doc.setFillColor(...config.color)
        doc.circle(p.x, p.y, 1.2, 'F')
        addText(`${p.score}`, p.x, p.y - 2, { fontSize: 7, color: config.color, align: 'center' })
      })

      // X-axis date labels (first and last only)
      addText(formatDate(sorted[0].assessed_at, isKo), graphX, graphY + graphH + 4, {
        fontSize: 6,
        color: COLORS.textSecondary,
      })
      addText(formatDate(sorted[sorted.length - 1].assessed_at, isKo), graphX + graphW, graphY + graphH + 4, {
        fontSize: 6,
        color: COLORS.textSecondary,
        align: 'right',
      })

      doc.setLineWidth(0.2)
      yPos = graphY + graphH + 10
    })
  }

  // === Section 4: AIS Grade Change (ASIA) ===
  const asiaItems = byType['ASIA']
  if (asiaItems && asiaItems.length > 0) {
    addSection(isKo ? 'AIS 등급 변화' : 'AIS Grade Change')

    const sorted = [...asiaItems].reverse() // oldest → newest
    sorted.forEach((a, i) => {
      checkPageBreak(10)
      const d = a.details as Record<string, unknown> | null
      const grade = (d?.aisGrade as string) ?? '-'
      const motorTotal = (d?.motorTotal as number) ?? '-'
      const lightTouchTotal = (d?.lightTouchTotal as number) ?? '-'
      const pinPrickTotal = (d?.pinPrickTotal as number) ?? '-'

      const prefix = i === 0 ? (isKo ? '초기' : 'Initial') : `#${i + 1}`
      addText(`${prefix}: ${formatDate(a.assessed_at, isKo)}`, margin, yPos, {
        fontSize: 9,
        color: COLORS.textSecondary,
      })
      addText(`Grade ${grade}`, margin + 65, yPos, { fontSize: 10, fontStyle: 'bold' })
      addText(`Motor:${motorTotal} LT:${lightTouchTotal} PP:${pinPrickTotal}`, margin + 95, yPos, {
        fontSize: 8,
        color: COLORS.textSecondary,
      })

      if (i < sorted.length - 1) {
        yPos += 4
        addText('↓', margin + 75, yPos, { fontSize: 10, color: COLORS.primary, align: 'center' })
        yPos += 5
      } else {
        yPos += 7
      }
    })
  }

  // === Footer (all pages) ===
  const totalPages = doc.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    addFooter()
    addText(`${i} / ${totalPages}`, pageWidth - margin, pageHeight - 12, {
      fontSize: 7,
      color: COLORS.textSecondary,
      align: 'right',
    })
  }

  return doc.output('blob')
}
