import type { UserGoal } from '@/types/user'
import type { Exercise } from '@/types/exercise'
import type { CaptureGuide } from '@/types/posture'

export const GOALS: UserGoal[] = [
  {
    id: 'posture_correction',
    name: 'Posture Correction',
    nameKo: '자세 교정',
    icon: '🧘',
    description: 'Improve your overall posture',
    descriptionKo: '전반적인 자세를 개선합니다',
  },
  {
    id: 'forward_head',
    name: 'Forward Head Fix',
    nameKo: '거북목 개선',
    icon: '🦒',
    description: 'Fix forward head posture',
    descriptionKo: '거북목 자세를 교정합니다',
  },
  {
    id: 'back_pain',
    name: 'Back Pain Relief',
    nameKo: '허리 통증 완화',
    icon: '💆',
    description: 'Relieve lower back pain',
    descriptionKo: '허리 통증을 완화합니다',
  },
  {
    id: 'shoulder_pain',
    name: 'Shoulder Pain Relief',
    nameKo: '어깨 통증 완화',
    icon: '💪',
    description: 'Relieve shoulder tension',
    descriptionKo: '어깨 긴장을 완화합니다',
  },
  {
    id: 'rehabilitation',
    name: 'Rehabilitation',
    nameKo: '재활 운동',
    icon: '🏥',
    description: 'Recover from injuries',
    descriptionKo: '부상에서 회복합니다',
  },
  {
    id: 'body_shape',
    name: 'Body Shape Correction',
    nameKo: '체형 교정',
    icon: '🎯',
    description: 'Correct body alignment',
    descriptionKo: '체형을 교정합니다',
  },
  {
    id: 'exercise_habit',
    name: 'Exercise Habit',
    nameKo: '운동 습관 만들기',
    icon: '📅',
    description: 'Build a regular exercise routine',
    descriptionKo: '규칙적인 운동 습관을 만듭니다',
  },
  {
    id: 'stretching',
    name: 'Stretching',
    nameKo: '스트레칭',
    icon: '🤸',
    description: 'Improve flexibility',
    descriptionKo: '유연성을 향상시킵니다',
  },
  {
    id: 'strength',
    name: 'Strength Building',
    nameKo: '근력 강화',
    icon: '🏋️',
    description: 'Build muscle strength',
    descriptionKo: '근력을 강화합니다',
  },
]

export const PAIN_AREAS = [
  { id: 'neck', name: 'Neck', nameKo: '목', x: 50, y: 12 },
  { id: 'left_shoulder', name: 'Left Shoulder', nameKo: '왼쪽 어깨', x: 30, y: 18 },
  { id: 'right_shoulder', name: 'Right Shoulder', nameKo: '오른쪽 어깨', x: 70, y: 18 },
  { id: 'upper_back', name: 'Upper Back', nameKo: '등 상부', x: 50, y: 25 },
  { id: 'lower_back', name: 'Lower Back', nameKo: '허리', x: 50, y: 38 },
  { id: 'left_elbow', name: 'Left Elbow', nameKo: '왼쪽 팔꿈치', x: 20, y: 35 },
  { id: 'right_elbow', name: 'Right Elbow', nameKo: '오른쪽 팔꿈치', x: 80, y: 35 },
  { id: 'left_wrist', name: 'Left Wrist', nameKo: '왼쪽 손목', x: 15, y: 48 },
  { id: 'right_wrist', name: 'Right Wrist', nameKo: '오른쪽 손목', x: 85, y: 48 },
  { id: 'left_hip', name: 'Left Hip', nameKo: '왼쪽 골반', x: 38, y: 48 },
  { id: 'right_hip', name: 'Right Hip', nameKo: '오른쪽 골반', x: 62, y: 48 },
  { id: 'left_knee', name: 'Left Knee', nameKo: '왼쪽 무릎', x: 40, y: 68 },
  { id: 'right_knee', name: 'Right Knee', nameKo: '오른쪽 무릎', x: 60, y: 68 },
  { id: 'left_ankle', name: 'Left Ankle', nameKo: '왼쪽 발목', x: 40, y: 88 },
  { id: 'right_ankle', name: 'Right Ankle', nameKo: '오른쪽 발목', x: 60, y: 88 },
]

export const EXERCISES: Exercise[] = [
  // ============================================
  // 실시간 피드백 운동 (기존)
  // ============================================
  {
    id: 'squat',
    name: 'Squat',
    nameKo: '스쿼트',
    description: 'A fundamental lower body exercise',
    descriptionKo: '기본적인 하체 운동입니다',
    category: 'strength',
    difficulty: 'beginner',
    exerciseType: 'realtime',
    duration: 60,
    defaultReps: 10,
    defaultSets: 3,
    restBetweenSets: 30,
    targetMuscles: ['quadriceps', 'glutes', 'hamstrings'],
    targetConditions: ['bow_legs', 'pelvic_tilt'],
    instructions: [
      'Stand with feet shoulder-width apart',
      'Lower your body by bending knees',
      'Keep your back straight',
      'Return to starting position',
    ],
    instructionsKo: [
      '발을 어깨 너비로 벌리고 서세요',
      '무릎을 굽혀 몸을 낮추세요',
      '등을 곧게 유지하세요',
      '시작 자세로 돌아가세요',
    ],
    checkpoints: [
      {
        name: 'Knee angle',
        nameKo: '무릎 각도',
        startAngle: 170,
        targetAngle: 90,
        completionThreshold: 160,
        joints: ['hip', 'knee', 'ankle'],
      },
    ],
    caloriesPerRep: 0.5,
  },
  {
    id: 'lunge',
    name: 'Lunge',
    nameKo: '런지',
    description: 'Single leg strengthening exercise',
    descriptionKo: '한 쪽 다리 강화 운동입니다',
    category: 'strength',
    difficulty: 'beginner',
    exerciseType: 'realtime',
    duration: 60,
    defaultReps: 10,
    defaultSets: 3,
    restBetweenSets: 30,
    targetMuscles: ['quadriceps', 'glutes', 'hamstrings'],
    instructions: [
      'Stand with feet hip-width apart',
      'Step forward with one leg',
      'Lower your hips until both knees are bent',
      'Push back to starting position',
    ],
    instructionsKo: [
      '발을 골반 너비로 벌리고 서세요',
      '한 발을 앞으로 내딛으세요',
      '양 무릎이 구부러질 때까지 엉덩이를 낮추세요',
      '시작 자세로 돌아가세요',
    ],
    checkpoints: [
      {
        name: 'Front knee angle',
        nameKo: '앞 무릎 각도',
        startAngle: 170,
        targetAngle: 90,
        completionThreshold: 160,
        joints: ['hip', 'knee', 'ankle'],
      },
    ],
    caloriesPerRep: 0.6,
  },
  {
    id: 'pushup',
    name: 'Push-up',
    nameKo: '푸쉬업',
    description: 'Classic upper body exercise',
    descriptionKo: '클래식한 상체 운동입니다',
    category: 'strength',
    difficulty: 'intermediate',
    exerciseType: 'realtime',
    duration: 60,
    defaultReps: 10,
    defaultSets: 3,
    restBetweenSets: 30,
    targetMuscles: ['chest', 'triceps', 'shoulders'],
    instructions: [
      'Start in plank position',
      'Lower your body until chest nearly touches floor',
      'Push back up to starting position',
      'Keep your core engaged',
    ],
    instructionsKo: [
      '플랭크 자세에서 시작하세요',
      '가슴이 거의 바닥에 닿을 때까지 몸을 낮추세요',
      '시작 자세로 다시 밀어 올리세요',
      '코어에 힘을 유지하세요',
    ],
    checkpoints: [
      {
        name: 'Elbow angle',
        nameKo: '팔꿈치 각도',
        startAngle: 170,
        targetAngle: 90,
        completionThreshold: 160,
        joints: ['shoulder', 'elbow', 'wrist'],
      },
    ],
    caloriesPerRep: 0.4,
  },
  {
    id: 'plank',
    name: 'Plank',
    nameKo: '플랭크',
    description: 'Core stabilization exercise',
    descriptionKo: '코어 안정화 운동입니다',
    category: 'core',
    difficulty: 'beginner',
    exerciseType: 'realtime',
    duration: 30,
    defaultReps: 1,
    defaultSets: 3,
    holdDuration: 30,
    restBetweenSets: 30,
    targetMuscles: ['core', 'shoulders', 'glutes'],
    targetConditions: ['scoliosis', 'lower_cross', 'pelvic_tilt'],
    instructions: [
      'Start in forearm plank position',
      'Keep your body in a straight line',
      'Engage your core and glutes',
      'Hold the position',
    ],
    instructionsKo: [
      '팔꿈치 플랭크 자세에서 시작하세요',
      '몸을 일직선으로 유지하세요',
      '코어와 둔근에 힘을 주세요',
      '자세를 유지하세요',
    ],
    checkpoints: [
      {
        name: 'Body alignment',
        nameKo: '몸 정렬',
        startAngle: 180,
        targetAngle: 180,
        completionThreshold: 170,
        joints: ['shoulder', 'hip', 'ankle'],
      },
    ],
    caloriesPerRep: 3,
  },
  {
    id: 'bridge',
    name: 'Bridge',
    nameKo: '브릿지',
    description: 'Glute and core strengthening',
    descriptionKo: '둔근과 코어 강화 운동입니다',
    category: 'core',
    difficulty: 'beginner',
    exerciseType: 'realtime',
    duration: 60,
    defaultReps: 10,
    defaultSets: 3,
    restBetweenSets: 30,
    targetMuscles: ['glutes', 'hamstrings', 'core'],
    targetConditions: ['lumbar_lordosis', 'pelvic_tilt', 'lower_cross'],
    instructions: [
      'Lie on your back with knees bent',
      'Lift your hips toward the ceiling',
      'Squeeze your glutes at the top',
      'Lower back down slowly',
    ],
    instructionsKo: [
      '무릎을 구부리고 등을 대고 누우세요',
      '엉덩이를 천장 방향으로 들어올리세요',
      '정점에서 둔근을 조이세요',
      '천천히 내려오세요',
    ],
    checkpoints: [
      {
        name: 'Hip elevation',
        nameKo: '엉덩이 높이',
        startAngle: 90,
        targetAngle: 170,
        completionThreshold: 100,
        joints: ['shoulder', 'hip', 'knee'],
      },
    ],
    caloriesPerRep: 0.3,
  },
  {
    id: 'crunch',
    name: 'Crunch',
    nameKo: '크런치',
    description: 'Core rehabilitation exercise for abdominal strengthening',
    descriptionKo: '복부 강화를 위한 코어 재활 운동입니다',
    category: 'core',
    difficulty: 'beginner',
    exerciseType: 'realtime',
    duration: 60,
    defaultReps: 15,
    defaultSets: 3,
    restBetweenSets: 30,
    targetMuscles: ['rectus abdominis', 'obliques'],
    targetConditions: ['lower_cross', 'lumbar_lordosis'],
    instructions: [
      'Lie on your back with knees bent',
      'Place hands behind your head or across chest',
      'Lift your shoulders off the ground by engaging your core',
      'Lower back down slowly with control',
    ],
    instructionsKo: [
      '무릎을 구부리고 등을 대고 누우세요',
      '손을 머리 뒤나 가슴 위에 올리세요',
      '코어에 힘을 주며 어깨를 바닥에서 들어올리세요',
      '천천히 조절하며 내려오세요',
    ],
    checkpoints: [
      {
        name: 'Upper body lift',
        nameKo: '상체 들기',
        startAngle: 180,
        targetAngle: 120,
        completionThreshold: 170,
        joints: ['shoulder', 'hip', 'knee'],
      },
    ],
    caloriesPerRep: 0.3,
  },
  {
    id: 'lying_leg_raise',
    name: 'Lying Leg Raise',
    nameKo: '라잉 레그 레이즈',
    description: 'Lower abdominal rehabilitation exercise',
    descriptionKo: '하복부 재활 운동입니다',
    category: 'core',
    difficulty: 'beginner',
    exerciseType: 'realtime',
    duration: 60,
    defaultReps: 12,
    defaultSets: 3,
    restBetweenSets: 30,
    targetMuscles: ['lower abs', 'hip flexors'],
    targetConditions: ['lower_cross', 'pelvic_tilt'],
    instructions: [
      'Lie flat on your back with legs extended',
      'Keep your lower back pressed to the floor',
      'Raise your legs to 90 degrees',
      'Lower legs slowly without touching the floor',
    ],
    instructionsKo: [
      '다리를 펴고 등을 대고 누우세요',
      '허리를 바닥에 붙이세요',
      '다리를 90도까지 들어올리세요',
      '바닥에 닿지 않게 천천히 내리세요',
    ],
    checkpoints: [
      {
        name: 'Leg raise angle',
        nameKo: '다리 들기 각도',
        startAngle: 180,
        targetAngle: 90,
        completionThreshold: 170,
        joints: ['shoulder', 'hip', 'ankle'],
      },
    ],
    caloriesPerRep: 0.4,
  },
  {
    id: 'good_morning',
    name: 'Good Morning',
    nameKo: '굿모닝',
    description: 'Lower back rehabilitation exercise for posterior chain',
    descriptionKo: '후면 사슬 강화를 위한 허리 재활 운동입니다',
    category: 'strength',
    difficulty: 'intermediate',
    exerciseType: 'realtime',
    duration: 60,
    defaultReps: 10,
    defaultSets: 3,
    restBetweenSets: 30,
    targetMuscles: ['erector spinae', 'hamstrings', 'glutes'],
    targetConditions: ['lumbar_lordosis', 'lower_cross'],
    instructions: [
      'Stand with feet shoulder-width apart',
      'Keep a slight bend in your knees',
      'Hinge at your hips and lower your torso',
      'Return to standing by driving hips forward',
    ],
    instructionsKo: [
      '발을 어깨 너비로 벌리고 서세요',
      '무릎을 살짝 구부리세요',
      '엉덩이를 뒤로 빼며 상체를 숙이세요',
      '엉덩이를 앞으로 밀며 일어나세요',
    ],
    checkpoints: [
      {
        name: 'Hip hinge angle',
        nameKo: '힙 힌지 각도',
        startAngle: 170,
        targetAngle: 90,
        completionThreshold: 160,
        joints: ['shoulder', 'hip', 'knee'],
      },
    ],
    caloriesPerRep: 0.5,
  },
  {
    id: 'side_lunge_realtime',
    name: 'Side Lunge (Realtime)',
    nameKo: '사이드 런지 (실시간)',
    description: 'Hip rehabilitation exercise with lateral movement',
    descriptionKo: '측면 움직임을 통한 고관절 재활 운동입니다',
    category: 'strength',
    difficulty: 'beginner',
    exerciseType: 'realtime',
    duration: 60,
    defaultReps: 10,
    defaultSets: 3,
    restBetweenSets: 30,
    targetMuscles: ['adductors', 'quadriceps', 'glutes'],
    targetConditions: ['knock_knees', 'bow_legs'],
    instructions: [
      'Stand with feet together',
      'Step wide to one side',
      'Bend the stepping knee while keeping other leg straight',
      'Push back to starting position',
    ],
    instructionsKo: [
      '발을 모으고 서세요',
      '한쪽으로 넓게 발을 디디세요',
      '디딘 쪽 무릎을 구부리고 다른 다리는 펴세요',
      '시작 자세로 돌아가세요',
    ],
    checkpoints: [
      {
        name: 'Knee bend angle',
        nameKo: '무릎 굽힘 각도',
        startAngle: 170,
        targetAngle: 90,
        completionThreshold: 160,
        joints: ['hip', 'knee', 'ankle'],
      },
    ],
    caloriesPerRep: 0.5,
  },
  {
    id: 'knee_pushup',
    name: 'Knee Push-up',
    nameKo: '니푸쉬업',
    description: 'Beginner-friendly push-up variation on knees',
    descriptionKo: '무릎을 대고 하는 초급 푸시업입니다',
    category: 'strength',
    difficulty: 'beginner',
    exerciseType: 'realtime',
    duration: 60,
    defaultReps: 12,
    defaultSets: 3,
    restBetweenSets: 30,
    targetMuscles: ['chest', 'triceps', 'shoulders'],
    instructions: [
      'Start in a modified plank position with knees on the ground',
      'Keep your body straight from head to knees',
      'Lower your chest toward the floor',
      'Push back up to starting position',
    ],
    instructionsKo: [
      '무릎을 바닥에 대고 변형된 플랭크 자세를 취하세요',
      '머리부터 무릎까지 일직선을 유지하세요',
      '가슴을 바닥 방향으로 내리세요',
      '시작 자세로 다시 밀어 올리세요',
    ],
    checkpoints: [
      {
        name: 'Elbow angle',
        nameKo: '팔꿈치 각도',
        startAngle: 170,
        targetAngle: 90,
        completionThreshold: 160,
        joints: ['shoulder', 'elbow', 'wrist'],
      },
    ],
    caloriesPerRep: 0.3,
  },
  {
    id: 'barbell_deadlift',
    name: 'Barbell Deadlift',
    nameKo: '바벨 데드리프트',
    description: 'Full body strength exercise for posterior chain and back rehabilitation',
    descriptionKo: '후면 사슬과 허리 재활을 위한 전신 근력 운동입니다',
    category: 'strength',
    difficulty: 'intermediate',
    exerciseType: 'realtime',
    duration: 60,
    defaultReps: 8,
    defaultSets: 3,
    restBetweenSets: 60,
    targetMuscles: ['erector spinae', 'glutes', 'hamstrings', 'quadriceps', 'traps'],
    targetConditions: ['lumbar_lordosis'],
    instructions: [
      'Stand with feet hip-width apart, barbell over mid-foot',
      'Hinge at hips and grip the bar outside your legs',
      'Keep back straight, lift by driving through heels',
      'Stand tall at the top, then lower with control',
    ],
    instructionsKo: [
      '발을 골반 너비로 벌리고 바벨을 발 중앙 위에 두세요',
      '엉덩이를 뒤로 빼며 바를 다리 바깥에서 잡으세요',
      '등을 곧게 유지하며 발뒤꿈치로 밀어 들어올리세요',
      '정점에서 서고, 조절하며 내리세요',
    ],
    checkpoints: [
      {
        name: 'Hip hinge angle',
        nameKo: '힙 힌지 각도',
        startAngle: 170,
        targetAngle: 90,
        completionThreshold: 160,
        joints: ['shoulder', 'hip', 'knee'],
      },
    ],
    caloriesPerRep: 0.8,
  },
  {
    id: 'barbell_row',
    name: 'Barbell Row',
    nameKo: '바벨 로우',
    description: 'Back strength exercise for round shoulder correction',
    descriptionKo: '라운드숄더 교정을 위한 등 근력 운동입니다',
    category: 'strength',
    difficulty: 'intermediate',
    exerciseType: 'realtime',
    duration: 60,
    defaultReps: 10,
    defaultSets: 3,
    restBetweenSets: 45,
    targetMuscles: ['lats', 'rhomboids', 'traps', 'rear deltoids', 'biceps'],
    targetConditions: ['round_shoulder', 'upper_cross'],
    instructions: [
      'Hinge forward at the hips with slight knee bend',
      'Grip the barbell with hands slightly wider than shoulder-width',
      'Pull the bar toward your lower chest',
      'Lower with control and repeat',
    ],
    instructionsKo: [
      '무릎을 살짝 구부리고 엉덩이에서 앞으로 숙이세요',
      '어깨 너비보다 약간 넓게 바벨을 잡으세요',
      '바를 아래 가슴 쪽으로 당기세요',
      '조절하며 내리고 반복하세요',
    ],
    checkpoints: [
      {
        name: 'Elbow pull angle',
        nameKo: '팔꿈치 당김 각도',
        startAngle: 170,
        targetAngle: 45,
        completionThreshold: 160,
        joints: ['shoulder', 'elbow', 'wrist'],
      },
    ],
    caloriesPerRep: 0.5,
  },
  {
    id: 'dumbbell_bentover_row',
    name: 'Dumbbell Bent-over Row',
    nameKo: '덤벨 벤트오버 로우',
    description: 'Unilateral back exercise for posture correction',
    descriptionKo: '자세 교정을 위한 한쪽씩 하는 등 운동입니다',
    category: 'strength',
    difficulty: 'intermediate',
    exerciseType: 'realtime',
    duration: 60,
    defaultReps: 10,
    defaultSets: 3,
    restBetweenSets: 45,
    targetMuscles: ['lats', 'rhomboids', 'traps', 'rear deltoids', 'biceps'],
    targetConditions: ['round_shoulder', 'shoulder_imbalance', 'upper_cross'],
    instructions: [
      'Place one knee and hand on a bench for support',
      'Hold dumbbell in the other hand with arm extended',
      'Pull the dumbbell toward your hip',
      'Lower with control and repeat',
    ],
    instructionsKo: [
      '한쪽 무릎과 손을 벤치에 올려 지지하세요',
      '다른 손에 덤벨을 들고 팔을 펴세요',
      '덤벨을 엉덩이 쪽으로 당기세요',
      '조절하며 내리고 반복하세요',
    ],
    checkpoints: [
      {
        name: 'Elbow pull angle',
        nameKo: '팔꿈치 당김 각도',
        startAngle: 170,
        targetAngle: 45,
        completionThreshold: 160,
        joints: ['shoulder', 'elbow', 'wrist'],
      },
    ],
    caloriesPerRep: 0.4,
  },
  {
    id: 'front_raise',
    name: 'Front Raise',
    nameKo: '프런트 레이즈',
    description: 'Shoulder rehabilitation exercise for anterior deltoids',
    descriptionKo: '전면 삼각근을 위한 어깨 재활 운동입니다',
    category: 'strength',
    difficulty: 'beginner',
    exerciseType: 'realtime',
    duration: 60,
    defaultReps: 12,
    defaultSets: 3,
    restBetweenSets: 30,
    targetMuscles: ['anterior deltoids', 'upper chest'],
    targetConditions: ['shoulder_imbalance'],
    instructions: [
      'Stand with feet shoulder-width apart, arms at sides',
      'Hold dumbbells with palms facing your thighs',
      'Raise arms forward to shoulder height',
      'Lower slowly and repeat',
    ],
    instructionsKo: [
      '발을 어깨 너비로 벌리고 팔을 옆에 두세요',
      '손바닥이 허벅지를 향하게 덤벨을 잡으세요',
      '팔을 앞으로 들어 어깨 높이까지 올리세요',
      '천천히 내리고 반복하세요',
    ],
    checkpoints: [
      {
        name: 'Arm raise angle',
        nameKo: '팔 들기 각도',
        startAngle: 0,
        targetAngle: 90,
        completionThreshold: 10,
        joints: ['hip', 'shoulder', 'elbow'],
      },
    ],
    caloriesPerRep: 0.3,
  },
  {
    id: 'upright_row',
    name: 'Upright Row',
    nameKo: '업라이트로우',
    description: 'Shoulder strengthening exercise for traps and deltoids',
    descriptionKo: '승모근과 삼각근 강화를 위한 어깨 운동입니다',
    category: 'strength',
    difficulty: 'intermediate',
    exerciseType: 'realtime',
    duration: 60,
    defaultReps: 10,
    defaultSets: 3,
    restBetweenSets: 45,
    targetMuscles: ['traps', 'deltoids', 'biceps'],
    targetConditions: ['shoulder_imbalance', 'round_shoulder'],
    instructions: [
      'Stand with feet shoulder-width apart',
      'Hold weights in front of thighs, palms facing body',
      'Pull weights up along your body to chin level',
      'Lower slowly and repeat',
    ],
    instructionsKo: [
      '발을 어깨 너비로 벌리고 서세요',
      '허벅지 앞에서 손바닥이 몸을 향하게 웨이트를 잡으세요',
      '몸을 따라 턱 높이까지 당기세요',
      '천천히 내리고 반복하세요',
    ],
    checkpoints: [
      {
        name: 'Elbow pull angle',
        nameKo: '팔꿈치 당김 각도',
        startAngle: 170,
        targetAngle: 60,
        completionThreshold: 160,
        joints: ['shoulder', 'elbow', 'wrist'],
      },
    ],
    caloriesPerRep: 0.4,
  },
  {
    id: 'bicycle_crunch',
    name: 'Bicycle Crunch',
    nameKo: '바이시클 크런치',
    description: 'Dynamic core exercise targeting obliques',
    descriptionKo: '복사근을 타겟으로 하는 동적 코어 운동입니다',
    category: 'core',
    difficulty: 'intermediate',
    exerciseType: 'realtime',
    duration: 60,
    defaultReps: 20,
    defaultSets: 3,
    restBetweenSets: 30,
    targetMuscles: ['obliques', 'rectus abdominis', 'hip flexors'],
    targetConditions: ['lower_cross', 'pelvic_tilt'],
    instructions: [
      'Lie on your back with hands behind head',
      'Lift shoulders off the ground and bring knees up',
      'Alternate touching elbow to opposite knee',
      'Keep a smooth pedaling motion',
    ],
    instructionsKo: [
      '등을 대고 누워 손을 머리 뒤에 두세요',
      '어깨를 들고 무릎을 올리세요',
      '팔꿈치와 반대쪽 무릎을 번갈아 터치하세요',
      '부드러운 페달링 동작을 유지하세요',
    ],
    checkpoints: [
      {
        name: 'Crunch angle',
        nameKo: '크런치 각도',
        startAngle: 180,
        targetAngle: 90,
        completionThreshold: 170,
        joints: ['shoulder', 'hip', 'knee'],
      },
    ],
    caloriesPerRep: 0.4,
  },
  {
    id: 'burpee',
    name: 'Burpee',
    nameKo: '버피 테스트',
    description: 'Full body exercise for cardiovascular fitness assessment',
    descriptionKo: '심폐 체력 평가를 위한 전신 운동입니다',
    category: 'strength',
    difficulty: 'advanced',
    exerciseType: 'realtime',
    duration: 60,
    defaultReps: 10,
    defaultSets: 3,
    restBetweenSets: 60,
    targetMuscles: ['full body', 'quadriceps', 'chest', 'shoulders', 'core'],
    instructions: [
      'Start standing with feet shoulder-width apart',
      'Drop into a squat and place hands on the floor',
      'Jump feet back to plank position',
      'Jump feet forward, then jump up with arms overhead',
    ],
    instructionsKo: [
      '발을 어깨 너비로 벌리고 서세요',
      '스쿼트 자세로 내려가 손을 바닥에 짚으세요',
      '발을 뒤로 점프하여 플랭크 자세를 취하세요',
      '발을 앞으로 점프하고 팔을 위로 들며 뛰세요',
    ],
    checkpoints: [
      {
        name: 'Squat depth',
        nameKo: '스쿼트 깊이',
        startAngle: 170,
        targetAngle: 90,
        completionThreshold: 160,
        joints: ['hip', 'knee', 'ankle'],
      },
    ],
    caloriesPerRep: 1.0,
  },

  // ============================================
  // 교정 운동 (가이드)
  // ============================================
  {
    id: 'chin_tuck',
    name: 'Chin Tuck',
    nameKo: '턱 당기기',
    description: 'Corrects forward head posture by strengthening deep neck flexors',
    descriptionKo: '심부 목 굴곡근을 강화하여 거북목을 교정합니다',
    category: 'correction',
    difficulty: 'beginner',
    exerciseType: 'guided',
    duration: 90,
    defaultReps: 10,
    defaultSets: 3,
    holdDuration: 5,
    restBetweenSets: 20,
    targetMuscles: ['deep neck flexors', 'longus colli'],
    targetConditions: ['forward_head', 'upper_cross'],
    instructions: [
      'Sit or stand with your back straight',
      'Pull your chin straight back, making a double chin',
      'Hold for 5 seconds',
      'Return to starting position and repeat',
    ],
    instructionsKo: [
      '등을 곧게 펴고 앉거나 서세요',
      '턱을 뒤로 당겨 이중턱을 만드세요',
      '5초간 유지하세요',
      '시작 자세로 돌아가 반복하세요',
    ],
    checkpoints: [],
    caloriesPerRep: 0.1,
    benefits: ['Strengthens deep neck flexors', 'Reduces neck strain', 'Improves head posture'],
    benefitsKo: ['심부 목 굴곡근 강화', '목 긴장 완화', '머리 자세 개선'],
    precautions: ['Do not push chin down, pull it back', 'Stop if you feel pain'],
    precautionsKo: ['턱을 아래로 누르지 말고 뒤로 당기세요', '통증이 느껴지면 중단하세요'],
    breathingTip: 'Breathe normally throughout the exercise',
    breathingTipKo: '운동 중 정상적으로 호흡하세요',
  },
  {
    id: 'neck_stretch',
    name: 'Neck Stretch',
    nameKo: '목 스트레칭',
    description: 'Stretches tight neck muscles to relieve tension',
    descriptionKo: '긴장된 목 근육을 스트레칭하여 긴장을 완화합니다',
    category: 'correction',
    difficulty: 'beginner',
    exerciseType: 'guided',
    duration: 90,
    defaultReps: 1,
    defaultSets: 3,
    holdDuration: 30,
    restBetweenSets: 10,
    targetMuscles: ['upper trapezius', 'levator scapulae', 'scalenes'],
    targetConditions: ['forward_head', 'shoulder_imbalance'],
    instructions: [
      'Sit or stand with good posture',
      'Slowly tilt your head to one side, ear toward shoulder',
      'Hold for 30 seconds',
      'Repeat on the other side',
    ],
    instructionsKo: [
      '바른 자세로 앉거나 서세요',
      '천천히 머리를 한쪽으로 기울여 귀가 어깨를 향하게 하세요',
      '30초간 유지하세요',
      '반대쪽도 반복하세요',
    ],
    checkpoints: [],
    caloriesPerRep: 0.1,
    benefits: ['Relieves neck tension', 'Improves flexibility', 'Reduces headaches'],
    benefitsKo: ['목 긴장 완화', '유연성 향상', '두통 감소'],
    precautions: ['Do not force the stretch', 'Keep shoulders relaxed'],
    precautionsKo: ['스트레칭을 강요하지 마세요', '어깨를 편안하게 유지하세요'],
    breathingTip: 'Exhale as you deepen the stretch',
    breathingTipKo: '스트레칭을 깊게 할 때 내쉬세요',
  },
  {
    id: 'chest_stretch',
    name: 'Chest Stretch (Door Stretch)',
    nameKo: '가슴 스트레칭 (도어 스트레칭)',
    description: 'Opens tight chest muscles to correct rounded shoulders',
    descriptionKo: '굳은 가슴 근육을 이완하여 라운드숄더를 교정합니다',
    category: 'correction',
    difficulty: 'beginner',
    exerciseType: 'guided',
    duration: 90,
    defaultReps: 1,
    defaultSets: 3,
    holdDuration: 30,
    restBetweenSets: 10,
    targetMuscles: ['pectoralis major', 'pectoralis minor', 'anterior deltoid'],
    targetConditions: ['round_shoulder', 'upper_cross', 'thoracic_kyphosis'],
    instructions: [
      'Stand in a doorway with arms on the frame at 90 degrees',
      'Step forward with one foot',
      'Lean forward until you feel a stretch in your chest',
      'Hold for 30 seconds',
    ],
    instructionsKo: [
      '문틀에 팔을 90도로 올려 서세요',
      '한 발을 앞으로 내딛으세요',
      '가슴에 스트레칭이 느껴질 때까지 앞으로 기울이세요',
      '30초간 유지하세요',
    ],
    checkpoints: [],
    caloriesPerRep: 0.1,
    benefits: ['Opens chest muscles', 'Improves shoulder posture', 'Enhances breathing'],
    benefitsKo: ['가슴 근육 이완', '어깨 자세 개선', '호흡 개선'],
    precautions: ['Do not overstretch', 'Keep core engaged'],
    precautionsKo: ['과도하게 스트레칭하지 마세요', '코어에 힘을 유지하세요'],
    breathingTip: 'Breathe deeply into your chest',
    breathingTipKo: '가슴으로 깊게 호흡하세요',
  },
  {
    id: 'wall_slide',
    name: 'Wall Slide (Wall Angel)',
    nameKo: '월 슬라이드 (월 엔젤)',
    description: 'Strengthens upper back and improves shoulder mobility',
    descriptionKo: '등 상부를 강화하고 어깨 가동성을 향상시킵니다',
    category: 'correction',
    difficulty: 'intermediate',
    exerciseType: 'guided',
    duration: 90,
    defaultReps: 10,
    defaultSets: 3,
    restBetweenSets: 30,
    targetMuscles: ['rhomboids', 'lower trapezius', 'serratus anterior'],
    targetConditions: ['round_shoulder', 'upper_cross', 'shoulder_imbalance'],
    instructions: [
      'Stand with back against a wall, feet 6 inches away',
      'Place arms against wall in "W" position',
      'Slowly slide arms up to "Y" position',
      'Return to "W" position and repeat',
    ],
    instructionsKo: [
      '벽에 등을 대고 서서 발을 벽에서 15cm 떨어트리세요',
      '팔을 벽에 대고 "W" 자세를 취하세요',
      '천천히 팔을 올려 "Y" 자세로 만드세요',
      '"W" 자세로 돌아가 반복하세요',
    ],
    checkpoints: [],
    caloriesPerRep: 0.2,
    benefits: ['Strengthens scapular muscles', 'Improves posture', 'Increases shoulder mobility'],
    benefitsKo: ['견갑골 근육 강화', '자세 개선', '어깨 가동성 증가'],
    precautions: ['Keep lower back flat against wall', 'Do not arch back'],
    precautionsKo: ['허리를 벽에 붙이세요', '등을 휘지 마세요'],
    breathingTip: 'Exhale as you slide arms up',
    breathingTipKo: '팔을 올릴 때 내쉬세요',
  },
  {
    id: 'pelvic_tilt',
    name: 'Pelvic Tilt',
    nameKo: '골반 틸트',
    description: 'Corrects pelvic alignment and reduces lower back strain',
    descriptionKo: '골반 정렬을 교정하고 허리 부담을 줄입니다',
    category: 'correction',
    difficulty: 'beginner',
    exerciseType: 'guided',
    duration: 90,
    defaultReps: 15,
    defaultSets: 3,
    restBetweenSets: 20,
    targetMuscles: ['transverse abdominis', 'rectus abdominis', 'glutes'],
    targetConditions: ['pelvic_tilt', 'lumbar_lordosis', 'lower_cross'],
    instructions: [
      'Lie on your back with knees bent, feet flat on floor',
      'Flatten your lower back against the floor by tilting pelvis',
      'Hold for 5 seconds',
      'Release and repeat',
    ],
    instructionsKo: [
      '무릎을 구부리고 발을 바닥에 대고 등을 대고 누우세요',
      '골반을 기울여 허리를 바닥에 붙이세요',
      '5초간 유지하세요',
      '이완하고 반복하세요',
    ],
    checkpoints: [],
    caloriesPerRep: 0.1,
    benefits: ['Strengthens core', 'Corrects pelvic alignment', 'Relieves lower back pain'],
    benefitsKo: ['코어 강화', '골반 정렬 교정', '허리 통증 완화'],
    precautions: ['Keep movement controlled', 'Do not hold breath'],
    precautionsKo: ['동작을 천천히 조절하세요', '숨을 참지 마세요'],
    breathingTip: 'Exhale as you tilt pelvis',
    breathingTipKo: '골반을 기울일 때 내쉬세요',
  },
  {
    id: 'cat_cow',
    name: 'Cat-Cow Stretch',
    nameKo: '고양이-낙타 운동 (캣카우)',
    description: 'Improves spine flexibility and relieves back tension',
    descriptionKo: '척추 유연성을 향상시키고 등 긴장을 완화합니다',
    category: 'correction',
    difficulty: 'beginner',
    exerciseType: 'guided',
    duration: 90,
    defaultReps: 10,
    defaultSets: 3,
    restBetweenSets: 20,
    targetMuscles: ['erector spinae', 'rectus abdominis', 'serratus anterior'],
    targetConditions: ['thoracic_kyphosis', 'scoliosis', 'lumbar_lordosis'],
    instructions: [
      'Start on hands and knees, hands under shoulders',
      'Inhale: Drop belly, lift head and tailbone (Cow)',
      'Exhale: Round spine, tuck chin and tailbone (Cat)',
      'Flow smoothly between positions',
    ],
    instructionsKo: [
      '손은 어깨 아래, 네 발로 엎드리세요',
      '들이쉬며: 배를 내리고 머리와 꼬리뼈를 들어올리세요 (낙타)',
      '내쉬며: 등을 둥글게 말고 턱과 꼬리뼈를 당기세요 (고양이)',
      '부드럽게 두 자세를 번갈아 하세요',
    ],
    checkpoints: [],
    caloriesPerRep: 0.2,
    benefits: ['Increases spinal mobility', 'Relieves back tension', 'Improves posture awareness'],
    benefitsKo: ['척추 가동성 증가', '등 긴장 완화', '자세 인식 향상'],
    precautions: ['Keep movements slow and controlled', 'Do not force range of motion'],
    precautionsKo: ['동작을 느리고 조절하여 하세요', '가동 범위를 무리하게 늘리지 마세요'],
    breathingTip: 'Coordinate breath with movement',
    breathingTipKo: '호흡과 동작을 일치시키세요',
  },
  {
    id: 'side_lunge',
    name: 'Side Lunge',
    nameKo: '사이드 런지',
    description: 'Strengthens inner and outer thighs, corrects leg alignment',
    descriptionKo: '허벅지 안쪽과 바깥쪽을 강화하고 다리 정렬을 교정합니다',
    category: 'correction',
    difficulty: 'intermediate',
    exerciseType: 'guided',
    duration: 90,
    defaultReps: 10,
    defaultSets: 3,
    restBetweenSets: 30,
    targetMuscles: ['adductors', 'abductors', 'quadriceps', 'glutes'],
    targetConditions: ['knock_knees', 'bow_legs'],
    instructions: [
      'Stand with feet together',
      'Step wide to one side, bending that knee',
      'Keep other leg straight, foot flat',
      'Push back to start and repeat on other side',
    ],
    instructionsKo: [
      '발을 모으고 서세요',
      '한쪽으로 넓게 발을 디디며 그쪽 무릎을 구부리세요',
      '다른 다리는 펴고 발을 바닥에 붙이세요',
      '시작 자세로 돌아가 반대쪽도 반복하세요',
    ],
    checkpoints: [],
    caloriesPerRep: 0.4,
    benefits: ['Strengthens leg muscles', 'Improves hip mobility', 'Corrects leg alignment'],
    benefitsKo: ['다리 근육 강화', '고관절 가동성 향상', '다리 정렬 교정'],
    precautions: ['Keep knee aligned with toes', 'Do not let knee go past toes'],
    precautionsKo: ['무릎이 발끝과 같은 방향을 향하게 하세요', '무릎이 발끝을 넘지 않게 하세요'],
    breathingTip: 'Exhale as you push back',
    breathingTipKo: '돌아올 때 내쉬세요',
  },

  // ============================================
  // 스트레칭 (가이드)
  // ============================================
  {
    id: 'hamstring_stretch',
    name: 'Hamstring Stretch',
    nameKo: '햄스트링 스트레칭',
    description: 'Stretches tight hamstrings to reduce lower back strain',
    descriptionKo: '굳은 햄스트링을 스트레칭하여 허리 부담을 줄입니다',
    category: 'stretching',
    difficulty: 'beginner',
    exerciseType: 'guided',
    duration: 90,
    defaultReps: 1,
    defaultSets: 3,
    holdDuration: 30,
    restBetweenSets: 10,
    targetMuscles: ['hamstrings', 'calves'],
    targetConditions: ['lumbar_lordosis', 'lower_cross', 'pelvic_tilt'],
    instructions: [
      'Sit on floor with one leg extended, other bent',
      'Reach toward your toes on the extended leg',
      'Hold when you feel a stretch in back of thigh',
      'Repeat on other side',
    ],
    instructionsKo: [
      '바닥에 앉아 한 다리는 펴고 다른 다리는 구부리세요',
      '펴진 다리의 발끝을 향해 손을 뻗으세요',
      '허벅지 뒤쪽에 스트레칭이 느껴지면 유지하세요',
      '반대쪽도 반복하세요',
    ],
    checkpoints: [],
    caloriesPerRep: 0.1,
    benefits: ['Increases hamstring flexibility', 'Reduces lower back tension', 'Improves posture'],
    benefitsKo: ['햄스트링 유연성 증가', '허리 긴장 완화', '자세 개선'],
    precautions: ['Do not bounce', 'Keep back straight'],
    precautionsKo: ['반동을 주지 마세요', '등을 곧게 유지하세요'],
    breathingTip: 'Exhale as you reach forward',
    breathingTipKo: '앞으로 뻗을 때 내쉬세요',
  },
  {
    id: 'it_band_stretch',
    name: 'IT Band Stretch',
    nameKo: 'IT밴드 스트레칭',
    description: 'Stretches the iliotibial band to relieve knee and hip tension',
    descriptionKo: '장경인대를 스트레칭하여 무릎과 골반 긴장을 완화합니다',
    category: 'stretching',
    difficulty: 'beginner',
    exerciseType: 'guided',
    duration: 90,
    defaultReps: 1,
    defaultSets: 3,
    holdDuration: 30,
    restBetweenSets: 10,
    targetMuscles: ['iliotibial band', 'tensor fasciae latae', 'gluteus medius'],
    targetConditions: ['knock_knees', 'bow_legs'],
    instructions: [
      'Stand with feet together near a wall for support',
      'Cross one leg behind the other',
      'Lean hips toward the wall on the side of back leg',
      'Hold when you feel stretch along outer thigh',
    ],
    instructionsKo: [
      '벽 옆에 서서 발을 모으세요',
      '한 다리를 다른 다리 뒤로 교차시키세요',
      '뒷다리 쪽으로 골반을 벽 방향으로 기울이세요',
      '허벅지 바깥쪽에 스트레칭이 느껴지면 유지하세요',
    ],
    checkpoints: [],
    caloriesPerRep: 0.1,
    benefits: ['Relieves IT band tightness', 'Reduces knee pain', 'Improves hip mobility'],
    benefitsKo: ['IT밴드 긴장 완화', '무릎 통증 감소', '고관절 가동성 향상'],
    precautions: ['Hold wall for balance', 'Do not twist spine'],
    precautionsKo: ['균형을 위해 벽을 잡으세요', '척추를 비틀지 마세요'],
    breathingTip: 'Breathe deeply and relax into the stretch',
    breathingTipKo: '깊게 호흡하며 스트레칭에 이완하세요',
  },
  {
    id: 'upper_trap_stretch',
    name: 'Upper Trapezius Stretch',
    nameKo: '상부 승모근 스트레칭',
    description: 'Relieves tension in upper shoulders and neck',
    descriptionKo: '어깨 위쪽과 목의 긴장을 완화합니다',
    category: 'stretching',
    difficulty: 'beginner',
    exerciseType: 'guided',
    duration: 90,
    defaultReps: 1,
    defaultSets: 3,
    holdDuration: 30,
    restBetweenSets: 10,
    targetMuscles: ['upper trapezius', 'levator scapulae'],
    targetConditions: ['forward_head', 'shoulder_imbalance', 'upper_cross'],
    instructions: [
      'Sit or stand with good posture',
      'Reach one hand behind your back',
      'Tilt head away from that side, ear toward opposite shoulder',
      'Use other hand to gently increase stretch',
    ],
    instructionsKo: [
      '바른 자세로 앉거나 서세요',
      '한 손을 등 뒤로 뻗으세요',
      '머리를 반대쪽으로 기울여 귀가 어깨를 향하게 하세요',
      '다른 손으로 부드럽게 스트레칭을 늘리세요',
    ],
    checkpoints: [],
    caloriesPerRep: 0.1,
    benefits: ['Relieves shoulder tension', 'Reduces neck stiffness', 'Improves range of motion'],
    benefitsKo: ['어깨 긴장 완화', '목 뻣뻣함 감소', '가동 범위 향상'],
    precautions: ['Do not force the stretch', 'Keep shoulders down'],
    precautionsKo: ['스트레칭을 강요하지 마세요', '어깨를 내리세요'],
    breathingTip: 'Exhale as you deepen the stretch',
    breathingTipKo: '스트레칭을 깊게 할 때 내쉬세요',
  },

  // ============================================
  // 재활 운동 (가이드)
  // ============================================
  {
    id: 'clamshell',
    name: 'Clamshell',
    nameKo: '클램쉘',
    description: 'Strengthens hip abductors for better hip stability',
    descriptionKo: '고관절 외전근을 강화하여 골반 안정성을 높입니다',
    category: 'rehabilitation',
    difficulty: 'beginner',
    exerciseType: 'guided',
    duration: 90,
    defaultReps: 15,
    defaultSets: 3,
    restBetweenSets: 20,
    targetMuscles: ['gluteus medius', 'gluteus minimus', 'external rotators'],
    targetConditions: ['bow_legs', 'pelvic_tilt', 'knock_knees'],
    instructions: [
      'Lie on your side with knees bent at 45 degrees',
      'Keep feet together, lift top knee like a clamshell opening',
      'Do not rotate your pelvis or back',
      'Lower slowly and repeat',
    ],
    instructionsKo: [
      '옆으로 누워 무릎을 45도로 구부리세요',
      '발을 붙인 채 위쪽 무릎을 조개가 열리듯 들어올리세요',
      '골반이나 등이 회전하지 않게 하세요',
      '천천히 내리고 반복하세요',
    ],
    checkpoints: [],
    caloriesPerRep: 0.2,
    benefits: ['Strengthens hip stabilizers', 'Improves hip alignment', 'Reduces knee stress'],
    benefitsKo: ['고관절 안정근 강화', '고관절 정렬 개선', '무릎 스트레스 감소'],
    precautions: ['Keep core engaged', 'Do not roll backward'],
    precautionsKo: ['코어에 힘을 유지하세요', '뒤로 굴러가지 마세요'],
    breathingTip: 'Exhale as you lift the knee',
    breathingTipKo: '무릎을 들어올릴 때 내쉬세요',
  },
  {
    id: 'hip_abduction',
    name: 'Hip Abduction (Side Leg Raise)',
    nameKo: '힙 어브덕션 (옆으로 다리 들기)',
    description: 'Strengthens outer hip muscles for pelvic stability',
    descriptionKo: '골반 안정성을 위해 고관절 바깥쪽 근육을 강화합니다',
    category: 'rehabilitation',
    difficulty: 'beginner',
    exerciseType: 'guided',
    duration: 90,
    defaultReps: 15,
    defaultSets: 3,
    restBetweenSets: 20,
    targetMuscles: ['gluteus medius', 'tensor fasciae latae'],
    targetConditions: ['bow_legs', 'pelvic_tilt'],
    instructions: [
      'Lie on your side with legs straight',
      'Lift top leg toward ceiling, keeping it straight',
      'Do not rotate hip forward',
      'Lower slowly and repeat',
    ],
    instructionsKo: [
      '옆으로 누워 다리를 곧게 펴세요',
      '위쪽 다리를 천장 방향으로 들어올리세요',
      '골반이 앞으로 회전하지 않게 하세요',
      '천천히 내리고 반복하세요',
    ],
    checkpoints: [],
    caloriesPerRep: 0.2,
    benefits: ['Strengthens hip abductors', 'Improves balance', 'Stabilizes pelvis'],
    benefitsKo: ['고관절 외전근 강화', '균형 향상', '골반 안정화'],
    precautions: ['Keep body in straight line', 'Do not lean back'],
    precautionsKo: ['몸을 일직선으로 유지하세요', '뒤로 기대지 마세요'],
    breathingTip: 'Exhale as you lift',
    breathingTipKo: '다리를 들어올릴 때 내쉬세요',
  },
  {
    id: 'dead_bug',
    name: 'Dead Bug',
    nameKo: '데드버그',
    description: 'Core stabilization while moving limbs',
    descriptionKo: '팔다리를 움직이며 코어를 안정화합니다',
    category: 'rehabilitation',
    difficulty: 'intermediate',
    exerciseType: 'guided',
    duration: 90,
    defaultReps: 10,
    defaultSets: 3,
    restBetweenSets: 30,
    targetMuscles: ['transverse abdominis', 'rectus abdominis', 'hip flexors'],
    targetConditions: ['scoliosis', 'lower_cross', 'pelvic_tilt'],
    instructions: [
      'Lie on back with arms up and knees bent at 90 degrees',
      'Press lower back into floor',
      'Slowly lower opposite arm and leg toward floor',
      'Return to start and repeat on other side',
    ],
    instructionsKo: [
      '등을 대고 누워 팔을 위로 올리고 무릎을 90도로 구부리세요',
      '허리를 바닥에 붙이세요',
      '반대쪽 팔과 다리를 천천히 바닥 방향으로 내리세요',
      '시작 자세로 돌아가 반대쪽도 반복하세요',
    ],
    checkpoints: [],
    caloriesPerRep: 0.3,
    benefits: ['Builds core stability', 'Protects spine', 'Improves coordination'],
    benefitsKo: ['코어 안정성 구축', '척추 보호', '협응력 향상'],
    precautions: ['Keep lower back pressed to floor', 'Move slowly and controlled'],
    precautionsKo: ['허리를 바닥에 붙이세요', '느리고 조절하여 움직이세요'],
    breathingTip: 'Exhale as you extend limbs',
    breathingTipKo: '팔다리를 뻗을 때 내쉬세요',
  },
]

export const CAPTURE_GUIDES: CaptureGuide[] = [
  {
    direction: 'front',
    instructions: [
      'Stand facing the camera',
      'Keep your arms at your sides',
      'Look straight ahead',
    ],
    instructionsKo: [
      '카메라를 정면으로 바라보고 서세요',
      '팔을 옆에 자연스럽게 내려놓으세요',
      '정면을 바라보세요',
    ],
    checkpoints: ['Full body visible', 'Standing straight', 'Arms visible'],
    checkpointsKo: ['전신이 보임', '똑바로 서 있음', '팔이 보임'],
  },
  {
    direction: 'side',
    instructions: [
      'Stand sideways to the camera',
      'Keep your arms at your sides',
      'Look straight ahead',
    ],
    instructionsKo: [
      '카메라를 향해 옆으로 서세요',
      '팔을 옆에 자연스럽게 내려놓으세요',
      '정면을 바라보세요',
    ],
    checkpoints: ['Full body visible', 'Profile view clear', 'Standing naturally'],
    checkpointsKo: ['전신이 보임', '측면 모습이 선명함', '자연스럽게 서 있음'],
  },
  {
    direction: 'back',
    instructions: [
      'Stand with your back to the camera',
      'Keep your arms at your sides',
      'Look straight ahead',
    ],
    instructionsKo: [
      '카메라에 등을 돌리고 서세요',
      '팔을 옆에 자연스럽게 내려놓으세요',
      '정면을 바라보세요',
    ],
    checkpoints: ['Full body visible', 'Back clearly visible', 'Standing straight'],
    checkpointsKo: ['전신이 보임', '등이 선명하게 보임', '똑바로 서 있음'],
  },
]

export const HAND_EXERCISES = [
  {
    id: 'finger_flexion',
    name: 'Finger Flexion/Extension',
    nameKo: '손가락 굴곡/신전',
    description: 'Open and close your hand completely',
    descriptionKo: '손을 완전히 펴고 주먹을 쥐는 운동',
    defaultReps: 10,
    defaultSets: 3,
    guide: [
      'Extend your fingers fully',
      'Slowly make a fist',
      'Hold for 5 seconds then release',
    ],
    guideKo: [
      '손가락을 완전히 펴세요',
      '천천히 주먹을 쥐세요',
      '5초간 유지 후 다시 펴세요',
    ],
  },
  {
    id: 'tendon_glide',
    name: 'Tendon Gliding',
    nameKo: '힘줄 미끄럼 운동',
    description: 'Move through different hand positions',
    descriptionKo: '다양한 손 자세로 이동하는 운동',
    defaultReps: 10,
    defaultSets: 3,
    guide: [
      'Start with fingers extended',
      'Curl fingertips toward palm (hook shape)',
      'Extend again then make a fist',
    ],
    guideKo: [
      '손가락을 펴고 시작하세요',
      '손가락 끝을 손바닥 쪽으로 구부리세요 (갈고리 모양)',
      '다시 펴고 주먹을 쥐세요',
    ],
  },
  {
    id: 'thumb_touch',
    name: 'Thumb-to-Finger Touch',
    nameKo: '엄지-손가락 터치',
    description: 'Touch each fingertip with your thumb',
    descriptionKo: '엄지로 각 손가락 끝을 터치하는 운동',
    defaultReps: 10,
    defaultSets: 3,
    guide: [
      'Touch thumb tip to index fingertip',
      'Touch thumb tip to middle fingertip',
      'Continue to ring and pinky fingers',
    ],
    guideKo: [
      '엄지와 검지 끝을 터치하세요',
      '엄지와 중지 끝을 터치하세요',
      '엄지와 약지, 소지 순서로 터치하세요',
    ],
  },
  {
    id: 'finger_spread',
    name: 'Finger Spread',
    nameKo: '손가락 벌리기',
    description: 'Spread your fingers apart',
    descriptionKo: '손가락을 최대한 벌리는 운동',
    defaultReps: 10,
    defaultSets: 3,
    guide: [
      'Keep all fingers together',
      'Spread fingers as wide as possible',
      'Hold for 5 seconds then bring together',
    ],
    guideKo: [
      '손가락을 모두 붙이세요',
      '손가락을 최대한 벌리세요',
      '5초간 유지 후 다시 모으세요',
    ],
  },
  {
    id: 'grip_squeeze',
    name: 'Grip Squeeze',
    nameKo: '그립 쥐기',
    description: 'Squeeze and hold a fist',
    descriptionKo: '주먹을 쥐고 유지하는 운동',
    defaultReps: 10,
    defaultSets: 3,
    guide: [
      'Start with hand open',
      'Squeeze into a tight fist',
      'Hold for 5 seconds then slowly release',
    ],
    guideKo: [
      '손을 편 상태로 시작하세요',
      '주먹을 꽉 쥐세요',
      '5초간 유지 후 천천히 펴세요',
    ],
  },
  {
    id: 'wrist_rotation',
    name: 'Wrist Rotation',
    nameKo: '손목 회전',
    description: 'Rotate your wrist in circles',
    descriptionKo: '손목을 원을 그리며 돌리는 운동',
    defaultReps: 10,
    defaultSets: 3,
    guide: [
      'Make a loose fist',
      'Slowly rotate wrist clockwise',
      'Then rotate counter-clockwise',
    ],
    guideKo: [
      '주먹을 가볍게 쥐세요',
      '손목을 시계 방향으로 천천히 돌리세요',
      '반시계 방향으로도 돌리세요',
    ],
  },
]

export const MEDIAPIPE_CONFIG = {
  pose: {
    modelComplexity: 1,
    smoothLandmarks: true,
    enableSegmentation: false,
    smoothSegmentation: false,
    minDetectionConfidence: 0.5,
    minTrackingConfidence: 0.5,
  },
  hands: {
    maxNumHands: 2,
    modelComplexity: 1,
    minDetectionConfidence: 0.5,
    minTrackingConfidence: 0.5,
  },
}

// 질환/조건 → 추천 운동 매핑
import type { TargetCondition } from '@/types/exercise'

export const CONDITION_EXERCISE_MAPPING: Record<TargetCondition, string[]> = {
  forward_head: ['chin_tuck', 'neck_stretch', 'upper_trap_stretch'],
  round_shoulder: ['chest_stretch', 'wall_slide'],
  upper_cross: ['chin_tuck', 'neck_stretch', 'chest_stretch', 'wall_slide', 'upper_trap_stretch'],
  shoulder_imbalance: ['wall_slide', 'upper_trap_stretch'],
  thoracic_kyphosis: ['chest_stretch', 'wall_slide', 'cat_cow'],
  lumbar_lordosis: ['pelvic_tilt', 'hamstring_stretch', 'cat_cow', 'dead_bug'],
  lower_cross: ['pelvic_tilt', 'hamstring_stretch', 'hip_abduction', 'cat_cow', 'dead_bug'],
  pelvic_tilt: ['pelvic_tilt', 'clamshell', 'hip_abduction', 'dead_bug'],
  scoliosis: ['cat_cow', 'side_lunge'],
  bow_legs: ['side_lunge', 'it_band_stretch', 'clamshell'],
  knock_knees: ['hip_abduction', 'clamshell', 'side_lunge'],
}
